ballerina-platform/module-ballerinax-sap.jco

ballerina/types.bal
=> Fix typo "DEFULT"

.gitignore, ballerina/client.bal, ballerina/test/ReadMe.md
=> Fin release workflow

.github/workflows/build-with-bal-test-graalvm.yml, .gitignore
=> Streamline multi repo checkout

.github/workflows/pull-request.yml
=> Add pull-request workflow

ballerina/Ballerina.toml, ballerina/Dependencies.toml, native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java
=> Fix data binding issue

README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/client.bal, ballerina/types.bal, build-config/resources/Ballerina.toml, examples/idoc_automation/Ballerina.toml, examples/idoc_automation/idoc automation.md, examples/order_idoc_listener/Ballerina.toml, examples/sap_inventory_update/Ballerina.toml, examples/sap_inventory_update/sap inventory update.md, native/src/main/java/io/ballerina/lib/sap/BallerinaDestinationDataProvider.java, native/src/main/java/io/ballerina/lib/sap/Client.java, native/src/main/java/io/ballerina/lib/sap/SAPConstants.java
Fixes:
1. Add union-type support for import params in RFC client
2. Add nill support for export params
3. Add Date support for Import params
4. Add byte array support for Import params
5. Fix version binding.
=> Fix param binding issues

native/src/main/java/io/ballerina/lib/sap/Client.java, native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java
=> Fix error capturing

.github/workflows/trivy-scan.yml, README.md
=> Fix trivy-scan.yml

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/client.bal, native/src/main/java/io/ballerina/lib/sap/Client.java, native/src/main/java/io/ballerina/lib/sap/SAPConstants.java, native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java
- Add support for Jco Structures.
- Add Date support for export params.
- Add export as a json/xml support.
- Add byte array support
Fixes:
=> Add support for JCo Structures

native/src/main/java/io/ballerina/lib/sap/parameterprocessor/ExportParameterProcessor.java
=> Fix data-binding issue in export params

native/src/main/java/io/ballerina/lib/sap/parameterprocessor/ExportParameterProcessor.java
=> Improve error logs for type cast

ballerina/types.bal
=> Make client configs optional

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/types.bal
=> Fix data binding with connectionCount

ballerina/Dependencies.toml, native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java
=> Add full stacktrace to the error 

ballerina/Ballerina.toml, ballerina/Dependencies.toml, native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java
=> Fix build failure due to conversion bug

ballerina/types.bal, native/src/main/java/io/ballerina/lib/sap/dataproviders/SAPServerDataProvider.java
=> Remove REP_DST and CC params

native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java, native/src/main/java/io/ballerina/lib/sap/parameterprocessor/ExportParameterProcessor.java
=> Minor improvements on errors and data binding

native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java
=> Fix `java.lang.Throwable.getCause()" is null` error

native/src/main/java/io/ballerina/lib/sap/IDocDispatcher.java, native/src/main/java/io/ballerina/lib/sap/SAPErrorCreator.java
=> Improve error messages

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/client.bal, ballerina/listener.bal, ballerina/types.bal, examples/idoc_automation/idoc automation.md, examples/order_idoc_listener/main.bal, examples/order_idoc_listener/order idoc listener.md, examples/sap_inventory_update/sap inventory update.md, gradle.properties, native/src/main/java/io/ballerina/lib/sap/Client.java, native/src/main/java/io/ballerina/lib/sap/Listener.java, native/src/main/java/io/ballerina/lib/sap/SAPConstants.java, native/src/main/java/io/ballerina/lib/sap/dataproviders/SAPDestinationDataProvider.java, native/src/main/java/io/ballerina/lib/sap/dataproviders/SAPServerDataProvider.java, native/src/main/java/io/ballerina/lib/sap/parameterprocessor/ExportParameterProcessor.java
=> Improve configs/export param mappings

native/src/main/java/io/ballerina/lib/sap/dataproviders/SAPDestinationDataProvider.java, native/src/main/java/io/ballerina/lib/sap/dataproviders/SAPServerDataProvider.java
=> Fix data binding error configs

ballerina/listener.bal, ballerina/types.bal
=> Improvements on error handling and configs

README.md, ballerina/Module.md, ballerina/Package.md
=> Fix example
